# Generated by Django 4.1.6 on 2023-08-05 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('farmer_code', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ICS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('register_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vfc_aeo', to='farmersdt.aeo')),
                ('fpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vfc_fpo', to='farmersdt.fpo')),
                ('ics', models.ManyToManyField(related_name='vfc_ics', to='farmersdt.ics')),
            ],
        ),
    ]
