# Generated by Django 4.1.6 on 2023-08-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ICS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('register_date', models.DateField()),
                ('fpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersdt.fpo')),
            ],
        ),
        migrations.CreateModel(
            name='VFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('panchayats', models.CharField(max_length=255)),
                ('revenue_village', models.CharField(max_length=255)),
                ('local_village', models.CharField(max_length=255)),
                ('aeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersdt.aeo')),
                ('fpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersdt.fpo')),
                ('ics', models.ManyToManyField(to='farmersdt.ics')),
            ],
        ),
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('panchayats', models.CharField(max_length=255)),
                ('fpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersdt.fpo')),
                ('ics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersdt.ics')),
                ('vfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersdt.vfc')),
            ],
        ),
        migrations.AddField(
            model_name='aeo',
            name='fpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersdt.fpo'),
        ),
    ]
