# Generated by Django 4.1.6 on 2023-08-05 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('farmersdt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vfc',
            name='local_village',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vfc_local_village', to='locations.localvillage'),
        ),
        migrations.AddField(
            model_name='ics',
            name='fpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ics_fpo', to='farmersdt.fpo'),
        ),
        migrations.AddField(
            model_name='farmers',
            name='fpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_fpo', to='farmersdt.fpo'),
        ),
        migrations.AddField(
            model_name='farmers',
            name='ics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_ics', to='farmersdt.ics'),
        ),
        migrations.AddField(
            model_name='farmers',
            name='panchayats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_panchayats', to='locations.panchayats'),
        ),
        migrations.AddField(
            model_name='farmers',
            name='vfc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_vfc', to='farmersdt.vfc'),
        ),
        migrations.AddField(
            model_name='aeo',
            name='fpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeo_fpo', to='farmersdt.fpo'),
        ),
    ]
