# Generated by Django 4.2.4 on 2023-08-04 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmersdt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeo',
            name='fpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeo_fpo', to='farmersdt.fpo'),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='fpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_fpo', to='farmersdt.fpo'),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='ics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_ics', to='farmersdt.ics'),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='vfc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_vfc', to='farmersdt.vfc'),
        ),
        migrations.AlterField(
            model_name='ics',
            name='fpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ics_fpo', to='farmersdt.fpo'),
        ),
        migrations.AlterField(
            model_name='vfc',
            name='aeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vfc_aeo', to='farmersdt.aeo'),
        ),
        migrations.AlterField(
            model_name='vfc',
            name='fpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vfc_fpo', to='farmersdt.fpo'),
        ),
        migrations.AlterField(
            model_name='vfc',
            name='ics',
            field=models.ManyToManyField(related_name='vfc_ics', to='farmersdt.ics'),
        ),
    ]
