# Generated by Django 4.1.6 on 2023-08-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersdt', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vfc',
            name='ics',
            field=models.ManyToManyField(blank=True, related_name='vfc_ics', to='farmersdt.ics'),
        ),
    ]
