# Generated by Django 4.2.4 on 2023-08-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmersdt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countrty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocalVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Panchayats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('panchayat_code', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panchayats_districts', to='locations.district')),
                ('fpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panchayat_fpo', to='farmersdt.fpo')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_country', to='locations.countrty')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('panchayats', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='revenuevillage_panchayats', to='locations.panchayats')),
            ],
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('local_village', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='postoffice_localvillage', to='locations.localvillage')),
            ],
        ),
        migrations.AddField(
            model_name='localvillage',
            name='revenue_village',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='localvillage_revenuevillage', to='locations.revenuevillage'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_state', to='locations.state'),
        ),
    ]
