# Generated by Django 4.1.6 on 2023-08-05 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localvillage',
            name='revenue_village',
        ),
        migrations.RemoveField(
            model_name='revenuevillage',
            name='panchayats',
        ),
        migrations.AddField(
            model_name='localvillage',
            name='panchayats',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='localvillage_panchayats', to='locations.panchayats'),
        ),
        migrations.AddField(
            model_name='revenuevillage',
            name='local_village',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='revenuevillage_local_village', to='locations.localvillage'),
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('revenue_village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postoffice_revenue_village', to='locations.revenuevillage')),
            ],
        ),
    ]
