# Generated by Django 4.1.6 on 2023-08-05 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_localvillage_revenue_village_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localvillage',
            name='panchayats',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='localvillage_panchayats', to='locations.revenuevillage'),
        ),
        migrations.AlterField(
            model_name='postoffice',
            name='revenue_village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postoffice_revenue_village', to='locations.localvillage'),
        ),
        migrations.AlterField(
            model_name='revenuevillage',
            name='local_village',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='revenuevillage_local_village', to='locations.panchayats'),
        ),
    ]
